apiVersion: apps/v1
kind: Deployment
metadata:
  name: studyjob-controller
  namespace: katib
  labels:
    app: studyjob-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studyjob-controller
  template:
    metadata:
      labels:
        app: studyjob-controller
    spec:
      serviceAccountName: studyjob-controller
      containers:
      - name: studyjob-controller
        image: katib/studyjob-controller
        imagePullPolicy: Always
