apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-template
  namespace: katib
data:
  defaultWorkerTemplate.yaml : |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{.WorkerID}}
      namespace: katib
    spec:
      template:
        spec:
          containers:
          - name: {{.WorkerID}}
            image: alpine
          restartPolicy: Never
