apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-volume
  namespace: katib
  labels:
    app: katib
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: katib
      type: local
