apiVersion: "kubeflow.org/v1alpha1"
kind: StudyController
metadata:
  namespace: katib
  labels:
    controller-tools.k8s.io: "1.0"
  name: grid-example
spec:
  studySpec:
      name: grid-example
      owner: crd
      optimizationtype: minimize
      objectivevaluename: Validation-accuracy
      optimizationgoal: 0.99
      metricsnames:
        - accuracy
      parameterconfigs:
        - name: --lr
          parametertype: double
          feasible:
            min: "0.01"
            max: "0.03"
        - name: --num-layers
          parametertype: int
          feasible:
            min: "2"
            max: "5"
        - name: --optimizer
          parametertype: categorical
          feasible:
            list:
            - sgd
            - adam
            - ftrl
  workerSpec:
    image: "katib/mxnet-mnist-example"
    command: 
        - "python"
        - "/mxnet/example/image-classification/train_mnist.py"
        - "--batch-size=64"
    gpu: 0
  suggestionSpec:
    suggestionAlgorithm: "grid"
    suggestionParameters:
      - 
          name: "DefaultGrid"
          value: "1"
      - 
          name: "--lr"
          value: "4"
