apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: studycontroller.kubeflow.org
spec:
  group: kubeflow.org
  version: v1alpha1
  names:
    kind: StudyController
    singular: studycontroller
    plural: studycontroller
