kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: study-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  verbs:
  - create
  - update
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
- apiGroups:
  - kubeflow.org
  resources:
  - studycontroller
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: study-controller
  namespace: katib
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: study-controller
  namespace: katib
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: study-controller
subjects:
- kind: ServiceAccount
  name: study-controller
  namespace: katib
