apiVersion: v1
kind: Service
metadata:
  name: vizier-suggestion-manual
  namespace: kubeflow
  labels:
    app: vizier
    component: suggestion-manual
spec:
  type: ClusterIP
  ports:
    - port: 6789
      protocol: TCP
      name: api
  selector:
    app: vizier
    component: suggestion-manual
